[package]
name = "tictactoe-logic"
version = "0.1.0"
edition = "2021"

[dependencies]
bon = "2.3.0"
rand = { version = "0.8.0", optional = true }

[features]
default = ["random"]
random = ["dep:rand"]
